### ISSUE TITLE
Wiki page missing

### ISSUE THREAD

**Issue by dkprabu** [IBM/detect-timeseriesdata-change#11]
@hovig I see the Wiki page is missing. I see you as the last editor on 11-Nov-2017. Are you working on any changes? Can you reinstate the page please?

**Comment by hovig** [comment]
@dkprabu - I've been tasked at that time to remove wikis from a list of projects assigned to me along with modifying READMEs, etc.. Specially the ones that are published as patterns.

**Comment by ljbennett62** [comment]
@hovig - i would like you to prioritize the secret project over this work given the deadline we have for launching in time for the Think Conference. fyi @dkprabu

**Comment by stevemar** [comment]
@dkprabu i brought the wiki page back. we normally delete them once they are published but if you have a need for it, that's OK. https://github.com/IBM/detect-timeseriesdata-change/wiki
