### ISSUE TITLE
update notebook to use new cloud object storage

### ISSUE THREAD

**Issue by stevemar** [IBM/detect-timeseriesdata-change#14]
this code pattern should be updated to use the new cloud object service (not the swift based one).

The file https://github.com/IBM/detect-timeseriesdata-change/blob/master/notebooks/watson_changepoint_detection.ipynb should be updated like this one was: IBM/pixiedust-facebook-analysis@b22714a -- as well as the instructions in the README.

If i recall correctly, @balajikadambi has updated a few notebooks already, suggest pinging him to get a better understanding.

**Comment by dkprabu** [comment]
@stevemart I have done the necessary changes. Please help replace the current .pynb file (https://github.com/IBM/detect-timeseriesdata-change/blob/master/notebooks/watson_changepoint_detection.ipynb) with this updated one (https://github.com/dkprabu/changepoint1/blob/master/changecloudstorage/watson_changepoint_detection.ipynb)

**Comment by stevemar** [comment]
@dkprabu you have push access to this repository, you can upload a new version by going to https://github.com/IBM/detect-timeseriesdata-change/tree/master/notebooks then drag and drop the new file.

**Comment by dkprabu** [comment]
@stevemart Thanks.. I have committed the new changes for Cloud storage as above.

**Comment by stevemar** [comment]
@dkprabu thank you very much for your detailed work in this major update!
