### ISSUE TITLE
most links in the "steps" don't work

### ISSUE THREAD

**Issue by stevemar** [IBM/detect-timeseriesdata-change#2]
clicking on the steps results in no change for steps 3-8, since the links don't lead to anywhere, see the rendered URL in the github page to get the correct link. links 1 and 2 work fine.

1. Sign up for the Data Science Experience
2. Create Bluemix services
3. Create Node-RED App and inject IoT data
4. Create the notebook
5. Add the data and configuraton file
6. Update the notebook with service credentials
7. Run the notebook
8. Download the results

**Comment by maheshwarishikha** [comment]
Updated Links.
