### ISSUE TITLE
add more explanation to the analysis

### ISSUE THREAD

**Issue by stevemar** [IBM/detect-timeseriesdata-change#3]
the analysis is a bit too brief, see other similar journeys with a more in-depth analysis: https://github.com/IBM/pixiedust-traffic-analysis#4-analyze-the-results and https://github.com/IBM/pixiedust-facebook-analysis#7-analyze-the-results

**Comment by maheshwarishikha** [comment]
More details has been added already on 24th Aug as per Laura Bennett's comment. Please review and let us know if more details need to be added.
