### ISSUE TITLE
Error reading json configuration file

### ISSUE THREAD

**Issue by cenyuzhang** [IBM/detect-timeseriesdata-change#6]
when reading from the json configuration file, I got the following error. jsonlite version i have is 1.5

Error: lexical error: invalid char in json text.
                                       <html><h1>Forbidden</h1><p>Acce
                     (right here) ------^

Traceback:

1. fromJSON(readLines(getObjectStorageFileWithCredentials_db8e182e477e43d185da8da8a5ddfecc("ChangePointDetection", 
 .     v_sampleConfigFileName)))
2. fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, 
 .     simplifyMatrix = simplifyMatrix, flatten = flatten, ...)
3. parseJSON(txt, bigint_as_char)
4. parse_string(txt, bigint_as_char)

<img width="1038" alt="error" src="https://user-images.githubusercontent.com/17069714/30236229-78f54bd4-94da-11e7-97f2-478ad8d7d2c2.png">

**Comment by stevemar** [comment]
@ManjulaGHM @vchahalibm see above issue

**Comment by dkprabu** [comment]
Looks like there seems to be a issue with your .json file "cpd_dsx_config.json"
Please verify the content and format of your .json file again.
I have provided the contents of the original .json file template.
Cut paste this into your .json and change only the values leaving alone other areas.

[
	{
	"paramname": "coltimestamp",
		"paramvalue": "TIMESTAMP"
	},
	{
	"paramname": "colsensorid",
		"paramvalue": "SENSORID"
	},
	{
	"paramname": "colsensorvalue",
		"paramvalue": "SENSORVALUE"
	},
	{
	"paramname": "sensorid",
		"paramvalue": "3B1"
	},
	{
	"paramname": "datatimeformat",
		"paramvalue": "%d-%m-%Y %H:%M:%S"
	},
	{
	"paramname": "intimezone",
		"paramvalue": "GMT"
	},
	{
	"paramname": "rangetimeformat",
		"paramvalue": "%Y%m%d %H:%M:%S"
	},
	{
	"paramname": "Pfrom",
		"paramvalue": "20160324 00:00:00"
	},
	{
	"paramname": "Pto",
		"paramvalue": "20160325 00:00:00"
	},
	{
	"paramname": "Cfrom",
		"paramvalue": "20160325 00:00:00"
	},
	{
	"paramname": "Cto",
		"paramvalue": "20160326 00:00:00"
	},
 	{
	"paramname": "thresholdpercent",
		"paramvalue": 25
	}
]

**Comment by dkprabu** [comment]
Do confirm if this works, elase pass me the contents of your .json file, let me have a look

**Comment by cenyuzhang** [comment]
@dkprabu thanks. Here is my .json config file. It looks the same as yours. Please let me know if there is is any issue with the file. (renamed to .txt since github doesn't accept .json attachment)

[cpd_dsx_config.txt](https://github.com/IBM/detect-timeseriesdata-change/files/1292764/cpd_dsx_config.txt)

**Comment by dkprabu** [comment]
@cenyuzhang I tried reading your json file and I am able to do so without any issues in my instance of DSX. So, there is no issue with your json file content. I have attached the steps to read the json file in the attachement. Please follow those and let me know if it works for you.

[CPD_Issue6_20170912.docx](https://github.com/IBM/detect-timeseriesdata-change/files/1294831/CPD_Issue6_20170912.docx)

**Comment by dkprabu** [comment]
@cenyuzhang and try this too.. if the problem persists..
https://github.com/jeroen/jsonlite/issues/106

**Comment by cenyuzhang** [comment]
@dkprabu thanks! the issue was solved. I will close the issue.
